---
spring:
  jpa:
    hibernate:
      ddl-auto: "validate"
  application:
    name: "subasta_manager"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
    distribution:
      percentiles:
        http:
          server:
            requests: 0.5,0.9,0.95,0.99
      slo:
        http:
          server:
            requests: 100ms,200ms,500ms,1s,2s
